In [62]:
from matplotlib import pyplot as ply
from scipy import stats
import numpy as np
import pandas as pd
import json
import seaborn as sns

%matplotlib inline

In [70]:
#Read file and set CSV df + decode using 'latin1'
ru_df = pd.read_csv('resources/ruvideos2.csv', engine='python')
ru_df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,gDuslQ9avLc,17.14.11,????? ? ?????? ?????? ?????????,?—? ?????,22,11/13/2017 4:09,"????? ? ??????|""?????? ?????????""|""?????? ????...",62408,334,190,50,https://i.ytimg.com/vi/gDuslQ9avLc/default.jpg,False,False,False,"???????????, ??? ????? ? ??????. ?????? ? ????..."
1,AOCJIFEA_jE,17.14.11,????? ????? #29. ???????? ??????,Druzhko Show,22,11/13/2017 12:32,"????? ?????|""??? ???????""|""????""|""?????""|""????...",330043,43841,2244,2977,https://i.ytimg.com/vi/AOCJIFEA_jE/default.jpg,False,False,False,"? 29 ??????? ?????? ??? ?????? ??????, ??? ???..."
2,VAWNQDgwwOM,17.14.11,???? ???? - ???? ????? ?????,????,24,11/13/2017 11:11,"????|""???????""|""????""|""????""|""??????""|""???????...",424596,49854,714,2944,https://i.ytimg.com/vi/VAWNQDgwwOM/default.jpg,False,False,False,http://kapitany.ru/!Yulik.cap - ????????? #???...
3,gknkFwKQfHg,17.14.11,?????? ????????? ? ???????,Hochland,22,11/13/2017 1:51,"???????|""???""|""???????""|""??? ???????????""|""???...",112851,3566,122,80,https://i.ytimg.com/vi/gknkFwKQfHg/default.jpg,False,False,False,*** ??? ???????? ??????????? ????? ????
4,3sYvZcwzZr8,17.14.11,????? ????????? ?? ???????? ?????????,????????,24,11/13/2017 11:52,"????????|""Sovergon""|""?????""|""????????""|""?????""...",243469,36216,631,1692,https://i.ytimg.com/vi/3sYvZcwzZr8/default.jpg,False,False,False,? ??????? ????????: http://kapitany.ru/!Soverg...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40734,OMmR9THjVKM,18.14.06,? ???? ????! (Story booth ?? ???????) ??????? ...,Pastime Time,22,6/13/2018 9:47,"story booth ?? ???????|""story booth ???????""|""...",129488,5893,164,990,https://i.ytimg.com/vi/OMmR9THjVKM/default.jpg,False,False,False,?????? ? Blade and Soul - https://bit.ly/2JoOq...
40735,tX7p7NtNVDE,18.14.06,??? ??????? ?????? 2 (????????),CaGArt,23,6/12/2018 5:38,"??????|""????""|""??????""|""??????""|""??????""|""????...",99163,4659,337,692,https://i.ytimg.com/vi/tX7p7NtNVDE/default.jpg,False,False,False,??? ??????? ?????? 2 (????????) ????...
40736,KAyj5Xm1C64,18.14.06,[ENG SUB] BTS PROM PARTY 2018 Intro + 2nd Gran...,DaisyxBTS 07,24,6/13/2018 8:51,[none],449611,24808,93,974,https://i.ytimg.com/vi/KAyj5Xm1C64/default.jpg,False,False,False,***I do NOT own anything. Just want to share t...
40737,4PiSLIrsSiY,18.14.06,????? ?????? ?????????/????????? ????????? + ?...,????? ????????,22,6/12/2018 20:23,"??? ??? ?????? ???????|""room tour bathroom""|""?...",14225,793,39,209,https://i.ytimg.com/vi/4PiSLIrsSiY/default.jpg,False,False,False,"????? ?????? ???????, ????????? ???????+ ?????..."
40738,Ehy5foVfKOE,18.14.06,?????? ??????. ????? ?????????!,Tubus Show,29,6/13/2018 5:50,"?????? ??????|""????? ???""|""reebok""|""????? ????...",52340,7708,133,1819,https://i.ytimg.com/vi/Ehy5foVfKOE/default.jpg,False,False,False,? 90-? ????? ???????? ???? ????????? ???????? ...

In [17]:
#read json file
file = open('resources/ru_catid.json')
ru_json = json.load(file)

In [19]:
#Replace category id with category name
length = len(ru_json["items"])
length

ru_df["category_id"] = ru_df["category_id"].astype(str)

for x in range(length):
    id_number = ru_json["items"][x]["id"]
    category_name = ru_json["items"][x]["snippet"]["title"]
    ru_df["category_id"] = ru_df["category_id"].replace({f"{id_number}": f"{category_name}"})
    
ru_df["category_id"] = ru_df["category_id"].replace({"29": "Nonprofits & Activism"})
    
ru_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,gDuslQ9avLc,17.14.11,ÐÐ°Ñ Ð°Ñ Ð¸ ÐÐ¾Ð»Ð¸Ð½Ð° ÑÑÐ°ÑÑÑ ÑÐºÐ¾...,Ð¢âÐ ÐÐÐÐÐ§,People & Blogs,2017-11-13T09:09:31.000Z,"Ð·Ð°Ñ Ð°Ñ Ð¸ Ð¿Ð¾Ð»Ð¸Ð½Ð°|""ÑÑÐ¸Ð¼ÑÑ ÑÐºÐ...",62408,334,190,50,https://i.ytimg.com/vi/gDuslQ9avLc/default.jpg,False,False,False,"ÐÐ½Ð°ÐºÐ¾Ð¼ÑÑÐµÑÑ, ÑÑÐ¾ ÐÐ°Ñ Ð°Ñ Ð¸ Ð..."
1,AOCJIFEA_jE,17.14.11,ÐÐ¸ÑÐ¶Ð° ÐÐµÐ¼Ð¾Ð² #29. ÐÐ¾Ð»ÑÑÐ¾Ð¸Ì Ð²...,Druzhko Show,People & Blogs,2017-11-13T17:32:11.000Z,"Ð±Ð¸ÑÐ¶Ð° Ð¼ÐµÐ¼Ð¾Ð²|""Ð»ÐµÐ² ÑÐ°Ð³Ð¸Ð½ÑÐ½""|...",330043,43841,2244,2977,https://i.ytimg.com/vi/AOCJIFEA_jE/default.jpg,False,False,False,Ð 29 Ð²ÑÐ¿ÑÑÐºÐµ ÐÑÑÐ¶ÐºÐ¾ Ð¨Ð¾Ñ Ð¡ÐµÑ...
2,VAWNQDgwwOM,17.14.11,Ð¥ÐÐÐ ÐÐ­ÐÐ - Ð¡ÐÐÐ Ð¡Ð ÐÐÐ Ð§Ð£Ð...,Ð®Ð»Ð¸Ðº,Entertainment,2017-11-13T16:11:31.000Z,"ÑÐ¼Ð¾Ñ|""ÐºÐ¾Ð¼ÐµÐ´Ð¸Ñ""|""Ð²Ð»Ð¾Ð³""|""Ð±Ð»Ð¾Ð³...",424596,49854,714,2944,https://i.ytimg.com/vi/VAWNQDgwwOM/default.jpg,False,False,False,http://kapitany.ru/!Yulik.cap - Ð¤Ð°ÐºÑÐ»ÑÑ...
3,gknkFwKQfHg,17.14.11,Ð¡Ð¾ÑÐ½Ð°Ñ ÐºÐµÑÐ°Ð´Ð¸Ð»ÑÑ Ñ ÐºÑÑÐ¸ÑÐµÐ¹,Hochland,People & Blogs,2017-11-13T06:51:10.000Z,"Ñ Ð¾Ñ Ð»Ð°Ð½Ð´|""ÑÑÑ""|""ÑÐµÑÐµÐ¿ÑÑ""|""ÐºÐ°...",112851,3566,122,80,https://i.ytimg.com/vi/gknkFwKQfHg/default.jpg,False,False,False,*** ÐºÐ°Ðº Ð³Ð¾ÑÐ¾Ð²Ð¸ÑÑ ÑÐµÑÑÐ¾ÑÐ°Ð½Ð½...
4,3sYvZcwzZr8,17.14.11,ÐÐÐÐÐ« Ð ÐÐÐÐ¢ÐÐÐÐ ÐÐ Ð¨ÐÐÐÐ¬Ð...,Ð¡Ð¾Ð²ÐµÑÐ³Ð¾Ð½,Entertainment,2017-11-13T16:52:36.000Z,"Ð¡Ð¾Ð²ÐµÑÐ³Ð¾Ð½|""Sovergon""|""ÐºÐ»Ð¸Ð¿Ñ""|""ÑÐ¾...",243469,36216,631,1692,https://i.ytimg.com/vi/3sYvZcwzZr8/default.jpg,False,False,False,â ÐÐÐÐÐ£Ð Ð¡ ÐÐÐÐÐ¢ÐÐÐ«: http://ka...

In [26]:
#Count #videos in each category
ru_count_df = pd.DataFrame(ru_df.groupby("category_id").count(), columns=["video_id"])
ru_count_df = ru_count_df.rename(columns={"video_id": "count"})
ru_count_df_views = ru_count_df.sort_values(by=["count"], ascending=False)
ru_count_df_views

                       count
category_id
People & Blogs         10350
Entertainment           5943
News & Politics         5402
Comedy                  3065
Film & Animation        3041
Howto & Style           2000
Sports                  1968
Music                   1895
Autos & Vehicles        1583
Nonprofits & Activism   1541
Science & Technology    1133
Gaming                  1043
Education                714
Pets & Animals           604
Travel & Events          262
Shows                    194
Movies                     1

In [47]:
group_by_category = ru_df.groupby('category_id')

In [32]:
#likes per category
likes_count = group_by_category['likes'].sum()
likes_count

category_id
Autos & Vehicles          21223727
Comedy                    69987601
Education                  2190395
Entertainment             98904908
Film & Animation          19150169
Gaming                    12541307
Howto & Style             12708499
Movies                        1732
Music                    120129951
News & Politics           15274142
Nonprofits & Activism     20005278
People & Blogs            73222107
Pets & Animals             2442850
Science & Technology      25866814
Shows                       532349
Sports                    11466103
Travel & Events             950559
Name: likes, dtype: int64

In [33]:
#dislikes per category
dislikes_count = group_by_category['dislikes'].sum()
dislikes_count

category_id
Autos & Vehicles          1473827
Comedy                    7156751
Education                  148439
Entertainment             9479944
Film & Animation          1185665
Gaming                     685296
Howto & Style              632259
Movies                        138
Music                     8069397
News & Politics           9178532
Nonprofits & Activism     7817721
People & Blogs           11792144
Pets & Animals             129947
Science & Technology      1435933
Shows                       93135
Sports                     706483
Travel & Events            112546
Name: dislikes, dtype: int64

In [50]:
#number of videos trending per category
trending_count = group_by_category['views'].count()
trending_count

category_id
Autos & Vehicles          1583
Comedy                    3065
Education                  714
Entertainment             5943
Film & Animation          3041
Gaming                    1043
Howto & Style             2000
Movies                       1
Music                     1895
News & Politics           5402
Nonprofits & Activism     1541
People & Blogs           10350
Pets & Animals             604
Science & Technology      1133
Shows                      194
Sports                    1968
Travel & Events            262
Name: views, dtype: int64

In [54]:
#comments per category
comment_count = group_by_category['comment_count'].sum()
comment_count

category_id
Autos & Vehicles          2245794
Comedy                    8269629
Education                  276845
Entertainment            14324340
Film & Animation          2138455
Gaming                    1623861
Howto & Style             1613128
Movies                        196
Music                    13197717
News & Politics           4724537
Nonprofits & Activism     4396835
People & Blogs           11694645
Pets & Animals             393434
Science & Technology      5700658
Shows                      127959
Sports                    1405578
Travel & Events            187532
Name: comment_count, dtype: int64

In [55]:
views_likes_dislikes = pd.DataFrame({
    'Trending': trending_count,
    'Likes': likes_count, 
    'Dislikes': dislikes_count,
    'Comments': comment_count
})
views_likes_dislikes
vlk_sorted = views_likes_dislikes.sort_values(by=["Trending"], ascending=False)
vlk_sorted

                       Trending      Likes  Dislikes  Comments
category_id
People & Blogs            10350   73222107  11792144  11694645
Entertainment              5943   98904908   9479944  14324340
News & Politics            5402   15274142   9178532   4724537
Comedy                     3065   69987601   7156751   8269629
Film & Animation           3041   19150169   1185665   2138455
Howto & Style              2000   12708499    632259   1613128
Sports                     1968   11466103    706483   1405578
Music                      1895  120129951   8069397  13197717
Autos & Vehicles           1583   21223727   1473827   2245794
Nonprofits & Activism      1541   20005278   7817721   4396835
Science & Technology       1133   25866814   1435933   5700658
Gaming                     1043   12541307    685296   1623861
Education                   714    2190395    148439    276845
Pets & Animals              604    2442850    129947    393434
Travel & Events             262     950559    112546    187532
Shows                       194     532349     93135    127959
Movies                        1       1732       138       196